### ISSUE TITLE
Error after fetching activity log list

### ISSUE THREAD

**Issue by lesaff** [simonepri/fitbit2garmin#1]
@simonepri Thanks for creating such a useful tool!

I got this error while running an export with start and end date.

OS: MacOS Sonoma 14.1
Python version: 3.11.6

Thanks!
Rudy

```
INFO:root:Activity log list fetched.
Traceback (most recent call last):
  File "/opt/homebrew/bin/fitbit2garmin", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fitbit2garmin/cli.py", line 161, in run
    cli()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fitbit2garmin/cli.py", line 27, in wrapper
    loop.run_until_complete(func(**kwargs))
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fitbit2garmin/cli.py", line 156, in dump_all
    await commands.dump_activity_tcx(cache_directory, directory, start_date, end_date)
  File "/opt/homebrew/lib/python3.11/site-packages/fitbit2garmin/commands.py", line 89, in dump_activity_tcx
    with activity_log_file_path.open("rbU") as fr:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rbU'
```

**Comment by simonepri** [comment]
It should be fixed now, can you try re-installing the package and run the command again?

**Comment by lesaff** [comment]
Your fix works! Thanks!
